docker4

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -7,11 +7,11 @@ WORKDIR /app
 # node_modules 제외 -> .dockerignore 파일 체크
 COPY . .
 
-# 의존성 설치 전에 캐시를 활용하여 더 빠른 빌드
-RUN npm install || (cat /app/npm-debug.log && exit 1)
+# 의존성 설치
+RUN npm install || (echo "npm install failed" && tail -n 50 /app/npm-debug.log && exit 1)
 
 # 빌드 -> /app/build
-RUN npm run build || (cat /app/npm-debug.log && exit 1)
+RUN npm run build || (echo "npm run build failed" && tail -n 50 /app/npm-debug.log && exit 1)
 
 # 스테이지 2 -> 서비스, nginx 이미지를 사용, 빌드 결과를 넣어서 구동
 FROM nginx:alpine
